language: php
php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly
before_script:
    - curl -s https://getcomposer.org/installer | php
    - php composer.phar install --dev
script: ./vendor/bin/atoum --glob Tests/Units/
matrix:
    allow_failures:
        - php: hhvm
        - php: hhvm-nightly
